name: gungame
main: asahina.koki.ai0.gungame.Plugin
version: 0.0.1
api-version: 1.20
description: 
commands:
  gg: # コマンドの名前じゃなきゃいけない
    aliases: [ gg ]
    description: Command description
    usage: Command usage